const data = [
    {

        id: 1,
        topic: "Frontend",
        Questions: [
            {
                que: "HTML stand for",
                op1: ["Hypermark Language",
                    "Hypermix language",
                    "Hypertext Markup Language",
                    "Hypertension Language"],
                correct: 'Hypertext Markup Language',
            },
            {
                que: "Which tag is used to create a check box ",
                op1: ["<checkbox>",
                    "<Input type=checkbox>",
                    "<type=checkbox",
                    "None of the above"],
                correct: '<Input type="checkbox">',
            },
            {
                que: "Which attribute set the text direction ",
                op1: ["dir",
                    "lang",
                    "direction",
                    "sub"],
                correct: "dir",
            },
            {
                que: "From which tag descriptive list starts ? ",
                op1: ["<LL>",
                    "<DL>",
                    "<LDL>",
                    "<DD>"],
                correct: "<DL>",
            },
            {
                que: "HTML is subset of which of the following",
                op1: [" GHL",
                    "SHL",
                    "SGHL",
                    "SGML"],
                correct: "SGML",
            },
            {
                que: "What are props into other components",
                op1: ["Injected",
                    "Both A and C",
                    "Method",
                    "None of the above"],
                correct: "Method",
            },
            {
                que: "React.js in MVC is ",
                op1: ["Model",
                    "Middleware",
                    "Method",
                    "Controller"],
                correct: "Controller",
            },
            {
                que: "What is state in react? ",
                op1: ["A prement storage",
                    " Internal storage of the component",
                    "Both A and B",
                    "None of the above"],
                correct: "Internal storage of the component",
            },
            {
                que: "What will happen if you render an input element with disabled = {false}",
                op1: [" It will be rendered as disabled",
                    "It will not be rendered at all",
                    "It will be rendered as enabled"],
                correct: " It will be rendered as enabled",
            },
            {
                que: "HTML stand for",
                op1: ["Destruction",
                    "State/Property Updates",
                    "Initialization",
                    "All of the above"],
                correct: "All of the above",
            },
            {
                que: "Which is not valid data type in Javascript",
                op1: ["Undefinded",
                    "Boolean",
                    "float",
                    "Number"],
                correct: "float",
            }
        ]
    },
    {
        id: 2,
        topic: "Backend",
        Questions: [
            {
                que: "What are Migrations in Django? ",
                op1: ["They are files saved in migrations directory.",
                    "They are created when you run makemigrations command.",
                    "Migrations are files where Django stores changes to your models.",
                    "All of the above"],
                correct: 'All of the above',
            },
            {
                que: "which of these is not a valid backend for caching in django? ",
                op1: ["django.core.cache.backends.sys.memory",
                    "django.core.cache.backends.db.DatabaseCache",
                    "django.core.cache.backends.locmem.LocMemCache",
                    "                 None of the above"],
                correct: 'django.core.cache.backends.sys.memory',
            },
            {
                que: "Which attribute set the text direction ",
                op1: ["dir",
                    "lang",
                    "direction",
                    "sub"],
                correct: "dir",
            },
            {
                que: "From which tag descriptive list starts ? ",
                op1: ["<LL>",
                    "<DL>",
                    "<LDL>",
                    "<DD>"],
                correct: "<DL>",
            },
            {
                que: "HTML is subset of which of the following",
                op1: [" GHL",
                    "SHL",
                    "SGHL",
                    "SGML"],
                correct: "SGML",
            },
            {
                que: "What are props into other components",
                op1: ["Injected",
                    "Both A and C",
                    "Method",
                    "None of the above"],
                correct: "Method",
            },
            {
                que: "React.js in MVC is ",
                op1: ["Model",
                    "Middleware",
                    "Method",
                    "Controller"],
                correct: "Controller",
            },
            {
                que: "What is state in react? ",
                op1: ["A prement storage",
                    " Internal storage of the component",
                    "Both A and B",
                    "None of the above"],
                correct: "Internal storage of the component",
            },
            {
                que: "What will happen if you render an input element with disabled = {false}",
                op1: [" It will be rendered as disabled",
                    "It will not be rendered at all",
                    "It will be rendered as enabled"],
                correct: " It will be rendered as enabled",
            },
            {
                que: "HTML stand for",
                op1: ["Destruction",
                    "State/Property Updates",
                    "Initialization",
                    "All of the above"],
                correct: "All of the above",
            },
            {
                que: "Which is not valid data type in Javascript",
                op1: ["Undefinded",
                    "Boolean",
                    "float",
                    "Number"],
                correct: "float",
            }
        ]
    },
    {
        id: 3,
        topic: "Data analysis",
        Questions: [
            {
                que: "What are Migrations in Django? ",
                op1: ["They are files saved in migrations directory.",
                    "They are created when you run makemigrations command.",
                    "Migrations are files where Django stores changes to your models.",
                    "All of the above"],
                correct: 'All of the above',
            },
            {
                que: "which of these is not a valid backend for caching in django? ",
                op1: ["django.core.cache.backends.sys.memory",
                    "django.core.cache.backends.db.DatabaseCache",
                    "django.core.cache.backends.locmem.LocMemCache",
                    "                 None of the above"],
                correct: 'django.core.cache.backends.sys.memory',
            },
            {
                que: "Which attribute set the text direction ",
                op1: ["dir",
                    "lang",
                    "direction",
                    "sub"],
                correct: "dir",
            },
            {
                que: "From which tag descriptive list starts ? ",
                op1: ["<LL>",
                    "<DL>",
                    "<LDL>",
                    "<DD>"],
                correct: "<DL>",
            },
            {
                que: "HTML is subset of which of the following",
                op1: [" GHL",
                    "SHL",
                    "SGHL",
                    "SGML"],
                correct: "SGML",
            },
            {
                que: "What are props into other components",
                op1: ["Injected",
                    "Both A and C",
                    "Method",
                    "None of the above"],
                correct: "Method",
            },
            {
                que: "React.js in MVC is ",
                op1: ["Model",
                    "Middleware",
                    "Method",
                    "Controller"],
                correct: "Controller",
            },
            {
                que: "What is state in react? ",
                op1: ["A prement storage",
                    " Internal storage of the component",
                    "Both A and B",
                    "None of the above"],
                correct: "Internal storage of the component",
            },
            {
                que: "What will happen if you render an input element with disabled = {false}",
                op1: [" It will be rendered as disabled",
                    "It will not be rendered at all",
                    "It will be rendered as enabled"],
                correct: " It will be rendered as enabled",
            },
            {
                que: "HTML stand for",
                op1: ["Destruction",
                    "State/Property Updates",
                    "Initialization",
                    "All of the above"],
                correct: "All of the above",
            },
            {
                que: "Which is not valid data type in Javascript",
                op1: ["Undefinded",
                    "Boolean",
                    "float",
                    "Number"],
                correct: "float",
            }
        ]
    },
    {
        id: 4,
        topic: "Blockchain",
        Questions: [
            {
                que: "What are Migrations in Django? ",
                op1: ["They are files saved in migrations directory.",
                    "They are created when you run makemigrations command.",
                    "Migrations are files where Django stores changes to your models.",
                    "All of the above"],
                correct: 'All of the above',
            },
            {
                que: "which of these is not a valid backend for caching in django? ",
                op1: ["django.core.cache.backends.sys.memory",
                    "django.core.cache.backends.db.DatabaseCache",
                    "django.core.cache.backends.locmem.LocMemCache",
                    "                 None of the above"],
                correct: 'django.core.cache.backends.sys.memory',
            },
            {
                que: "Which attribute set the text direction ",
                op1: ["dir",
                    "lang",
                    "direction",
                    "sub"],
                correct: "dir",
            },
            {
                que: "From which tag descriptive list starts ? ",
                op1: ["<LL>",
                    "<DL>",
                    "<LDL>",
                    "<DD>"],
                correct: "<DL>",
            },
            {
                que: "HTML is subset of which of the following",
                op1: [" GHL",
                    "SHL",
                    "SGHL",
                    "SGML"],
                correct: "SGML",
            },
            {
                que: "What are props into other components",
                op1: ["Injected",
                    "Both A and C",
                    "Method",
                    "None of the above"],
                correct: "Method",
            },
            {
                que: "React.js in MVC is ",
                op1: ["Model",
                    "Middleware",
                    "Method",
                    "Controller"],
                correct: "Controller",
            },
            {
                que: "What is state in react? ",
                op1: ["A prement storage",
                    " Internal storage of the component",
                    "Both A and B",
                    "None of the above"],
                correct: "Internal storage of the component",
            },
            {
                que: "What will happen if you render an input element with disabled = {false}",
                op1: [" It will be rendered as disabled",
                    "It will not be rendered at all",
                    "It will be rendered as enabled"],
                correct: " It will be rendered as enabled",
            },
            {
                que: "HTML stand for",
                op1: ["Destruction",
                    "State/Property Updates",
                    "Initialization",
                    "All of the above"],
                correct: "All of the above",
            },
            {
                que: "Which is not valid data type in Javascript",
                op1: ["Undefinded",
                    "Boolean",
                    "float",
                    "Number"],
                correct: "float",
            }
        ]
    },
    {
        id: 5,
        topic: "Software developer",
        Questions: [
            {
                que: "What are Migrations in Django? ",
                op1: ["They are files saved in migrations directory.",
                    "They are created when you run makemigrations command.",
                    "Migrations are files where Django stores changes to your models.",
                    "All of the above"],
                correct: 'All of the above',
            },
            {
                que: "which of these is not a valid backend for caching in django? ",
                op1: ["django.core.cache.backends.sys.memory",
                    "django.core.cache.backends.db.DatabaseCache",
                    "django.core.cache.backends.locmem.LocMemCache",
                    "                 None of the above"],
                correct: 'django.core.cache.backends.sys.memory',
            },
            {
                que: "Which attribute set the text direction ",
                op1: ["dir",
                    "lang",
                    "direction",
                    "sub"],
                correct: "dir",
            },
            {
                que: "From which tag descriptive list starts ? ",
                op1: ["<LL>",
                    "<DL>",
                    "<LDL>",
                    "<DD>"],
                correct: "<DL>",
            },
            {
                que: "HTML is subset of which of the following",
                op1: [" GHL",
                    "SHL",
                    "SGHL",
                    "SGML"],
                correct: "SGML",
            },
            {
                que: "What are props into other components",
                op1: ["Injected",
                    "Both A and C",
                    "Method",
                    "None of the above"],
                correct: "Method",
            },
            {
                que: "React.js in MVC is ",
                op1: ["Model",
                    "Middleware",
                    "Method",
                    "Controller"],
                correct: "Controller",
            },
            {
                que: "What is state in react? ",
                op1: ["A prement storage",
                    " Internal storage of the component",
                    "Both A and B",
                    "None of the above"],
                correct: "Internal storage of the component",
            },
            {
                que: "What will happen if you render an input element with disabled = {false}",
                op1: [" It will be rendered as disabled",
                    "It will not be rendered at all",
                    "It will be rendered as enabled"],
                correct: " It will be rendered as enabled",
            },
            {
                que: "HTML stand for",
                op1: ["Destruction",
                    "State/Property Updates",
                    "Initialization",
                    "All of the above"],
                correct: "All of the above",
            },
            {
                que: "Which is not valid data type in Javascript",
                op1: ["Undefinded",
                    "Boolean",
                    "float",
                    "Number"],
                correct: "float",
            }
        ]
    },
    {
        id: 6,
        topic: "Learning Style",
        Questions: [
            {
                que: "What kind of book would you like to read for fun? ",
                op1: ["A book with lots of pictures in it.",
                    "A book with lots of words in it.",
                    " A book with word searches or crossword puzzles"],
                correct: '',
            },
            {
                que: "When you are not sure how to spell a word, what are you most likely to do? ",
                op1: ["Write it down to see if it looks right",
                    "Spell it out loud to see if it sounds right",
                    "Trace the letters in the air (finger spelling)"],
                correct: '',
            },
            {
                que: " You're out shopping for clothes, and you're waiting in line to pay. What are you most likely to do while you are waiting? ",
                op1: ["Look around at other clothes on the racks",
                    "Talk to the person next to you in line",
                    "Fidget or move back and forth"],
                correct: "",
            },
            {
                que: "When you see the word cat, what do you do first? ",
                op1: ["Picture a cat in your mind",
                    "Say the word cat to yourself",
                    "Think about being with a cat (petting it or hearing it purr)"],
                correct: "",
            },
            {
                que: "What's the best way for you to study for a test?",
                op1: ["Read the book or your notes and review pictures or charts",
                    "Have someone ask you questions that you can answer out loud",
                    "Make up index cards that you can review"],
                correct: "",
            },
            {
                que: "What's the best way for you to learn about how something works (like a computer or a video game)?",
                op1: ["Get someone to show you",
                    "Read about it or listen to someone explain it",
                    "Figure it out on your own"],
                correct: "",
            },
            {
                que: " If you went to a school dance, what would you be most likely to remember the next day?",
                op1: ["The faces of the people who were there",
                    " The music that was played",
                    "The dance moves you did and the food you ate"],
                correct: "",
            },
            {
                que: "What do you find most distracting when you are trying to study?",
                op1: ["People walking past you",
                    "  Loud noises",
                    " An uncomfortable chair,"
                ],
                correct: "",
            },
        ]
    }
]


export default data