# Generated by Django 4.1.5 on 2023-02-05 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_log',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='user',
            name='streak',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
