# Generated by Django 4.1.5 on 2023-02-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizerapp', '0002_alter_mcqgenerator_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqgenerator',
            name='pdf_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mcqgenerator',
            name='summary',
            field=models.CharField(default='', max_length=200),
        ),
    ]
