# Generated by Django 4.1.5 on 2023-02-05 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summarizerapp', '0003_mcqgenerator_pdf_name_mcqgenerator_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=200)),
                ('answer', models.CharField(default='', max_length=200)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summarizerapp.mcqgenerator')),
            ],
        ),
    ]
