# Generated by Django 4.1.5 on 2023-02-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0002_testmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmarks',
            name='marks',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
